apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod
type: Opaque
stringData:
  connectionString: "Server=terraform-20260818041445880600000004.c1wke22u2wo0.us-west-1.rds.amazonaws.com;Port=3306;Database=cns_crm_db;User=admin1;Password=password123;"
