apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-service-monitor
  namespace: prod
  labels:
    release: prometheus
    app: metrics
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s